id: PE1442FD8
initial_creation_type: input
source_metadata:
  title: 'MSV 1,04: Varṣāvastu'
  language: zh
  volumes:
    c675051f72b94d09835cf86952792954:
      title: Piṇḍoddāna
      base_file: Piṇḍoddāna.txt
      work_id: W02E00592
    7635030396734de7a7caab90991c8b8a:
      title: Uddāna 1
      base_file: Uddāna 1.txt
      work_id: WDBA4727F
    16752c342efa436288c720b288bc5669:
      title: Uddāna 2
      base_file: Uddāna 2.txt
      work_id: W456F5C92
    7ca3b39718fb4832ac3fed8cfdca9286:
      title: Uddāna 3
      base_file: Uddāna 3.txt
      work_id: WA2362B48
  chapter_to_tile: {}
created_at: '2022-03-01T22:15:13.364129'
last_modified_at: '2022-03-01T22:15:13.364136'
